version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - db-data:/app  # Persist the SQLite database
    networks:
      - app-network

  frontend:
    build: 
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  db-data:  # Named volume for database persistence

networks:
  app-network:
    driver: bridge
